-- ─────────────────────────────────────────────────────────────────────────────
-- db/schema.sql
-- Canonical schema, pre-Phase-2 baseline. Generated by hand from migrations
-- 001–006 as a starting point. Regenerated by `npm run db:dump` once the
-- staging Supabase project is provisioned and the existing migrations have
-- been applied to it.
--
-- READ THIS FILE BEFORE WRITING ANY SUPABASE QUERY (Phase 2 §0.2).
-- Quote the relevant CREATE TABLE block verbatim in your checkpoint report.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── users ────────────────────────────────────────────────────────────────────
create table public.users (
  id         uuid primary key default gen_random_uuid(),
  slug       text unique not null check (slug in ('heo','masuri')),
  name       text not null,
  created_at timestamptz default now()
);

-- ── missing_signals ──────────────────────────────────────────────────────────
create table public.missing_signals (
  id           uuid primary key default gen_random_uuid(),
  from_user    uuid not null references public.users(id),
  intensity    smallint not null check (intensity between 1 and 3),
  acked_at     timestamptz,
  ack_token    text unique,
  created_at   timestamptz default now()
);

-- ── thinking_pings ───────────────────────────────────────────────────────────
create table public.thinking_pings (
  id          uuid primary key default gen_random_uuid(),
  from_user   uuid not null references public.users(id),
  to_user     uuid not null references public.users(id),
  seen_at     timestamptz,
  created_at  timestamptz default now()
);

-- ── angry_buzzes ─────────────────────────────────────────────────────────────
create table public.angry_buzzes (
  id            uuid primary key default gen_random_uuid(),
  from_user     uuid not null references public.users(id),
  need_type     text not null check (need_type in ('space','presence','vent','fix')),
  context_note  text,
  resolved_at   timestamptz,
  expires_at    timestamptz not null,
  created_at    timestamptz default now()
);

-- ── reunion_dates ────────────────────────────────────────────────────────────
-- NOTE: Phase 2 migrates this into important_dates and drops it post-stability.
-- Current columns: label, label_en (NOT label_vi).
create table public.reunion_dates (
  id          uuid primary key default gen_random_uuid(),
  label       text not null,
  label_en    text,
  target_date date not null,
  is_current  boolean not null default true,
  created_at  timestamptz default now()
);

-- ── push_subscriptions ───────────────────────────────────────────────────────
create table public.push_subscriptions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.users(id),
  endpoint   text unique not null,
  p256dh     text not null,
  auth       text not null,
  user_agent text,
  created_at timestamptz default now()
);

-- ── notification_prefs ───────────────────────────────────────────────────────
-- Phase 2 §4.4 adds: surprise_enabled, gmgn_enabled, date_planning_enabled,
-- outfit_enabled, important_date_enabled.
create table public.notification_prefs (
  user_id          uuid primary key references public.users(id),
  missing_enabled  boolean default true,
  thinking_enabled boolean default true,
  hug_kiss_enabled boolean default true,
  angry_enabled    boolean default true,
  quiet_start      time,
  quiet_end        time,
  updated_at       timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Phase 1.5 notebook tables (migration 004 + 006 fixes)
-- ─────────────────────────────────────────────────────────────────────────────

-- ── daily_pages ──────────────────────────────────────────────────────────────
create table public.daily_pages (
  id              uuid primary key default gen_random_uuid(),
  for_user        uuid not null references public.users(id),
  scheduled_for   date not null,
  status          text not null default 'draft'
                    check (status in ('draft','approved','published','archived')),
  title_vi        text,
  title_en        text,
  topic           text,
  difficulty      smallint default 2 check (difficulty between 1 and 3),
  cards           jsonb not null default '[]'::jsonb,
  generation_meta jsonb,
  approved_at     timestamptz,
  published_at    timestamptz,
  completed_at    timestamptz,
  created_at      timestamptz default now()
);

-- ── vocabulary ───────────────────────────────────────────────────────────────
create table public.vocabulary (
  id                uuid primary key default gen_random_uuid(),
  for_user          uuid not null references public.users(id),
  word_en           text not null,
  word_vi           text,
  pos               text,
  example           text,
  source_kind       text not null default 'page'
                      check (source_kind in ('page','masuri_card','ask_masuri','letter')),
  source_page_id    uuid references public.daily_pages(id),
  source_letter_id  uuid,
  self_confidence   smallint default 2 check (self_confidence between 1 and 3),
  saved_at          timestamptz default now()
);

-- ── letters ──────────────────────────────────────────────────────────────────
-- Phase 2 §17.2 extends kind: + 'love_note','surprise','gm','gn'. Two_truths stays.
create table public.letters (
  id              uuid primary key default gen_random_uuid(),
  from_user       uuid not null references public.users(id),
  to_user         uuid not null references public.users(id),
  kind            text not null
                    check (kind in ('weekly_letter','vocab_card','encouragement','two_truths')),
  prompt_id       text,
  body            text not null,
  language        text not null default 'en'
                    check (language in ('vi','en','mixed')),
  attachments     jsonb,
  in_reply_to     uuid references public.letters(id),
  scheduled_for   timestamptz default now(),
  delivered_at    timestamptz default now(),
  seen_at         timestamptz,
  created_at      timestamptz default now()
);

-- ── letter_prompts ───────────────────────────────────────────────────────────
create table public.letter_prompts (
  id            uuid primary key default gen_random_uuid(),
  prompt_vi     text not null,
  prompt_en     text not null,
  starter_words jsonb,
  difficulty    smallint not null default 2 check (difficulty between 1 and 5),
  active        boolean not null default true,
  created_at    timestamptz default now()
);

-- ── streaks ──────────────────────────────────────────────────────────────────
create table public.streaks (
  user_id              uuid primary key references public.users(id),
  current_streak       int not null default 0,
  longest_streak       int not null default 0,
  last_active_date     date,
  rest_days_remaining  int not null default 1,
  rest_days_used_at    date[] not null default '{}',
  rest_replenished_at  timestamptz default now(),
  updated_at           timestamptz default now()
);

-- ── notebook_prefs ───────────────────────────────────────────────────────────
create table public.notebook_prefs (
  user_id                uuid primary key references public.users(id),
  daily_reminder_time    time not null default '20:00',
  daily_reminder_enabled boolean not null default true,
  ask_masuri_enabled     boolean not null default true,
  letter_reply_enabled   boolean not null default true,
  preferred_topics       text[] not null default array['daily','feelings','food'],
  updated_at             timestamptz default now()
);

-- ── ask_masuri_threads ───────────────────────────────────────────────────────
create table public.ask_masuri_threads (
  id              uuid primary key default gen_random_uuid(),
  from_user       uuid not null references public.users(id),
  word_en         text,
  question_text   text not null,
  context_word    text,
  question_note   text,
  source_page_id  uuid references public.daily_pages(id),
  reply_text      text,
  replied_at      timestamptz,
  seen_at         timestamptz,
  thanked_at      timestamptz,
  created_at      timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- End of pre-Phase-2 schema. New Phase 2 tables begin at migration 007.
-- ─────────────────────────────────────────────────────────────────────────────
