-- ─────────────────────────────────────────────────────────────────────────────
-- db/schema.sql
-- Canonical schema, pre-Phase-2 baseline.
-- Reflects the exact state of the staging Supabase project after applying
-- migrations 001, 003, 004, 006 (002 and 005 deliberately skipped — staging
-- has no real Phase 1 user data; test users seeded separately).
--
-- READ THIS FILE BEFORE WRITING ANY SUPABASE QUERY (Phase 2 §0.2).
-- Quote the relevant CREATE TABLE block verbatim in your checkpoint report.
--
-- Verified against TypeScript types generated by
-- mcp__supabase__generate_typescript_types on 2026-05-29.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── users ────────────────────────────────────────────────────────────────────
create table public.users (
  id           uuid primary key default gen_random_uuid(),
  slug         text unique not null,
  display_name text not null,
  full_name    text not null,
  pronoun      text not null,
  timezone     text not null default 'Asia/Ho_Chi_Minh',
  created_at   timestamptz default now()
);

-- ── missing_signals ──────────────────────────────────────────────────────────
create table public.missing_signals (
  id              uuid primary key default gen_random_uuid(),
  from_user       uuid not null references public.users(id),
  intensity       smallint not null check (intensity in (1, 2, 3)),
  acknowledged_at timestamptz,
  created_at      timestamptz default now()
);
create index on public.missing_signals (created_at desc);

-- ── thinking_pings ───────────────────────────────────────────────────────────
create table public.thinking_pings (
  id         uuid primary key default gen_random_uuid(),
  from_user  uuid not null references public.users(id),
  to_user    uuid not null references public.users(id),
  kind       text not null check (kind in ('thinking', 'hug', 'kiss')),
  seen_at    timestamptz,
  created_at timestamptz default now()
);
create index on public.thinking_pings (to_user, seen_at, created_at desc);

-- ── angry_buzzes ─────────────────────────────────────────────────────────────
-- IMPORTANT: This table is NEVER queried for display in the UI.
-- No history view anywhere. Discord receives the realtime signal;
-- DB row is for closed-loop state only.
create table public.angry_buzzes (
  id             uuid primary key default gen_random_uuid(),
  from_user      uuid not null references public.users(id),
  need_type      text not null check (need_type in ('space', 'presence', 'vent', 'fix')),
  context_note   text,
  resolved_at    timestamptz,
  dan_reply      text check (dan_reply in ('sorry', 'on_my_way', 'talk_in_10', 'heard_you')),
  dan_replied_at timestamptz,
  created_at     timestamptz default now()
);
create index on public.angry_buzzes (resolved_at, created_at desc);

-- ── reunion_dates ────────────────────────────────────────────────────────────
-- NOTE: Phase 2 §4.2 migrates this into important_dates and drops it
-- post-stability. Current columns: label, label_en (NOT label_vi).
create table public.reunion_dates (
  id          uuid primary key default gen_random_uuid(),
  label       text not null,
  label_en    text,
  target_date date not null,
  is_current  boolean not null default true,
  created_at  timestamptz default now()
);

-- ── push_subscriptions ───────────────────────────────────────────────────────
create table public.push_subscriptions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.users(id),
  endpoint   text unique not null,
  p256dh     text not null,
  auth       text not null,
  user_agent text,
  created_at timestamptz default now()
);

-- ── notification_prefs ───────────────────────────────────────────────────────
-- Phase 2 §4.4 adds the 5 *_enabled flags below.
create table public.notification_prefs (
  user_id                uuid primary key references public.users(id),
  missing_enabled        boolean default true,
  thinking_enabled       boolean default true,
  hug_kiss_enabled       boolean default true,
  angry_enabled          boolean default true,
  quiet_start            time,
  quiet_end              time,
  -- Phase 2 additions (migration 010):
  surprise_enabled       boolean not null default true,
  gmgn_enabled           boolean not null default true,
  date_planning_enabled  boolean not null default true,
  outfit_enabled         boolean not null default true,
  important_date_enabled boolean not null default true,
  updated_at             timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Phase 1.5 notebook tables (migration 004 + 006 corrections)
-- ─────────────────────────────────────────────────────────────────────────────

-- ── daily_pages ──────────────────────────────────────────────────────────────
-- One page per calendar day per user. Status: draft → approved → published → completed.
create table public.daily_pages (
  id              uuid primary key default gen_random_uuid(),
  for_user        uuid not null references public.users(id),
  scheduled_for   date not null,
  status          text not null default 'draft'
                    check (status in ('draft','approved','published','archived')),
  title_vi        text not null,
  title_en        text not null,
  topic           text not null,
  difficulty      smallint not null check (difficulty between 1 and 5),
  cards           jsonb not null default '[]'::jsonb,
  generated_by    text not null default 'routine'
                    check (generated_by in ('routine','manual','masuri')),
  generation_meta jsonb,
  approved_by     uuid references public.users(id),
  approved_at     timestamptz,
  published_at    timestamptz,
  completed_at    timestamptz,
  created_at      timestamptz default now()
);
create unique index daily_pages_user_date_uidx
  on public.daily_pages (for_user, scheduled_for)
  where status != 'archived';
create index daily_pages_user_status_idx
  on public.daily_pages (for_user, status, scheduled_for desc);

-- ── vocabulary ───────────────────────────────────────────────────────────────
create table public.vocabulary (
  id                   uuid primary key default gen_random_uuid(),
  user_id              uuid not null references public.users(id),
  word_en              text not null,
  word_vi              text not null,
  example_en           text,
  example_vi           text,
  pos                  text,
  source_page_id       uuid references public.daily_pages(id) on delete set null,
  source_kind          text not null default 'page'
                         check (source_kind in ('page','masuri_card','ask_masuri','letter')),
  saved_at             timestamptz default now(),
  last_reviewed_at     timestamptz,
  review_count         int not null default 0,
  self_confidence      smallint not null default 0
                         check (self_confidence between -1 and 1),
  constraint vocabulary_user_word_unique unique (user_id, word_en)
);
create index vocabulary_user_saved_idx
  on public.vocabulary (user_id, saved_at desc);
create index vocabulary_user_confidence_idx
  on public.vocabulary (user_id, self_confidence, last_reviewed_at);

-- ── ask_masuri_threads ───────────────────────────────────────────────────────
create table public.ask_masuri_threads (
  id              uuid primary key default gen_random_uuid(),
  from_user       uuid not null references public.users(id),
  to_user         uuid not null references public.users(id),
  context_word    text,
  context_source  jsonb,
  question_note   text,
  reply_text      text,
  reply_audio_url text,
  replied_at      timestamptz,
  seen_at         timestamptz,
  created_at      timestamptz default now()
);
create index ask_masuri_from_user_idx
  on public.ask_masuri_threads (from_user, created_at desc);
create index ask_masuri_to_user_unseen_idx
  on public.ask_masuri_threads (to_user, replied_at, created_at desc);

-- ── letters ──────────────────────────────────────────────────────────────────
-- Phase 2 §17.2 extends kind: + 'love_note','surprise','gm','gn'. two_truths stays.
-- (Migration 007 applied the CHECK constraint extension below.)
create table public.letters (
  id              uuid primary key default gen_random_uuid(),
  from_user       uuid not null references public.users(id),
  to_user         uuid not null references public.users(id),
  kind            text not null
                    check (kind in ('weekly_letter','vocab_card','encouragement','two_truths',
                                    'love_note','surprise','gm','gn')),
  prompt_id       text,
  body            text not null,
  language        text not null default 'en'
                    check (language in ('vi','en','mixed')),
  attachments     jsonb,
  in_reply_to     uuid references public.letters(id),
  scheduled_for   timestamptz default now(),
  delivered_at    timestamptz default now(),
  seen_at         timestamptz,
  created_at      timestamptz default now()
);
create index letters_to_user_idx
  on public.letters (to_user, seen_at, delivered_at desc);
create index letters_from_user_kind_idx
  on public.letters (from_user, kind, created_at desc);

-- ── letter_prompts ───────────────────────────────────────────────────────────
create table public.letter_prompts (
  id            uuid primary key default gen_random_uuid(),
  prompt_vi     text not null,
  prompt_en     text not null,
  starter_words jsonb,
  difficulty    smallint not null default 2 check (difficulty between 1 and 5),
  active        boolean not null default true,
  created_at    timestamptz default now()
);

-- ── streaks ──────────────────────────────────────────────────────────────────
create table public.streaks (
  user_id              uuid primary key references public.users(id),
  current_streak       int not null default 0,
  longest_streak       int not null default 0,
  last_active_date     date,
  rest_days_remaining  int not null default 1,
  rest_days_used_at    date[] not null default '{}',
  rest_replenished_at  timestamptz default now(),
  updated_at           timestamptz default now()
);

-- ── notebook_prefs ───────────────────────────────────────────────────────────
create table public.notebook_prefs (
  user_id                uuid primary key references public.users(id),
  daily_reminder_time    time not null default '20:00',
  daily_reminder_enabled boolean not null default true,
  ask_masuri_enabled     boolean not null default true,
  letter_reply_enabled   boolean not null default true,
  preferred_topics       text[] not null default array['daily','feelings','food'],
  tts_rate               numeric not null default 0.9 check (tts_rate between 0.5 and 2.0),
  updated_at             timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS: all tables have RLS enabled. anon SELECT is granted on read-friendly
-- tables only. angry_buzzes, push_subscriptions, notification_prefs, and
-- notebook_prefs are server-only (no anon policy, no anon SELECT).
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────────────
-- Phase 2A — scheduled message infrastructure (migrations 007–010)
-- ─────────────────────────────────────────────────────────────────────────────

-- ── surprise_pool (migration 008) ────────────────────────────────────────────
-- Masuri's pre-written surprise messages. Shuffle-bag deliveries draw from here.
create table public.surprise_pool (
  id           uuid primary key default gen_random_uuid(),
  body         text not null,
  language     text not null default 'vi' check (language in ('vi','en','mixed')),
  weight       int not null default 1,
  attachments  jsonb,
  author       uuid not null references public.users(id),
  created_at   timestamptz default now(),
  retired_at   timestamptz
);
create index surprise_pool_active_idx on public.surprise_pool (retired_at, created_at desc);

-- ── surprise_deliveries (migration 008) ──────────────────────────────────────
-- Bookkeeping: which pool items have been delivered in which shuffle round.
-- Separate from `letters` because `letters` is the user-visible delivery and
-- this table is shuffle-bag state — different concern.
create table public.surprise_deliveries (
  id            uuid primary key default gen_random_uuid(),
  pool_id       uuid not null references public.surprise_pool(id),
  letter_id     uuid not null references public.letters(id),
  delivered_at  timestamptz not null default now(),
  shuffle_round int not null
);
create index surprise_deliveries_pool_idx  on public.surprise_deliveries (pool_id, delivered_at desc);
create index surprise_deliveries_round_idx on public.surprise_deliveries (shuffle_round, delivered_at desc);

-- ── recurring_letters (migration 009) ────────────────────────────────────────
-- GM/GN auto-note configuration. One row per active recurring schedule.
-- Pool rotates linearly (not shuffled): each tick advances `last_pool_index`,
-- wraps when reaching the end. Idempotent within a day via `last_delivered_at`.
create table public.recurring_letters (
  id                uuid primary key default gen_random_uuid(),
  from_user         uuid not null references public.users(id),
  to_user           uuid not null references public.users(id),
  kind              text not null check (kind in ('gm','gn')),
  pool              jsonb not null,
  send_at_local     time not null,
  timezone          text not null default 'Asia/Ho_Chi_Minh',
  enabled           boolean not null default true,
  last_delivered_at timestamptz,
  last_pool_index   int not null default -1,
  created_at        timestamptz default now()
);
create unique index recurring_letters_unique_kind_per_pair
  on public.recurring_letters (from_user, to_user, kind);

-- All three Phase 2A tables have RLS enabled and NO anon policies
-- (service-role only access — like notification_prefs, push_subscriptions).

-- ─────────────────────────────────────────────────────────────────────────────
-- End of schema. Phase 2B tables (calendar, important dates) begin at 011+.
-- ─────────────────────────────────────────────────────────────────────────────
